version: '3.6'
services:
  portainer:
    image: portainer/portainer-ee:latest
    restart: unless-stopped
    hostname: 'portainer.nas-apps.pepotheitdog.com'
    container_name: portainer
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 9443/tcp
      - 9000/tcp
    logging:
      driver: "json-file"
    healthcheck: 
      test: "wget --no-verbose --tries=1 --spider http://localhost:9000 || exit 1"
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 5s
networks:
  default: 
    external: true
    name: nas-apps
volumes:
  portainer-data:
